name: where-the-fit

services:
  postgres:
    image: postgres:16
    container_name: wtf-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: victor123
      POSTGRES_DB: wtf_db
    ports:
      - "5432:5432"
    volumes:
      - wtf-pg-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  wtf-pg-data:
    name: wtf-pg-data